// ============================================================
// SUPABASE CLIENT — Realtime Message Board Backend
// ============================================================

import {
  createClient,
  type SupabaseClient,
  type RealtimeChannel,
} from "@supabase/supabase-js";

const SUPABASE_URL = "https://fllqdhvvnqoayugohzld.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_mM9VIE_SOUb956b_7UeTzw_n9QaNuiL";

export const supabase: SupabaseClient = createClient(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
);

// ── Types matching the DB schema ──────────────────
export interface DbMessage {
  id: string;
  project_id: string;
  q_num: number;
  sender: string;
  text: string;
  created_at: string;
  read_by: string[];
}

// ── Online detection ───────────────────────────────
let _online = navigator.onLine;
window.addEventListener("online", () => {
  _online = true;
});
window.addEventListener("offline", () => {
  _online = false;
});
export function isOnline(): boolean {
  return _online;
}

// ── Message CRUD ───────────────────────────────────

export async function fetchMessages(projectId: string): Promise<DbMessage[]> {
  const { data, error } = await supabase
    .from("messages")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: true });
  if (error) {
    console.error("Supabase fetchMessages:", error);
    return [];
  }
  return data ?? [];
}

export async function fetchMessagesByQuestion(
  qNum: number,
  projectId: string,
): Promise<DbMessage[]> {
  const { data, error } = await supabase
    .from("messages")
    .select("*")
    .eq("project_id", projectId)
    .eq("q_num", qNum)
    .order("created_at", { ascending: true });
  if (error) {
    console.error("Supabase fetchByQ:", error);
    return [];
  }
  return data ?? [];
}

export async function insertMessage(
  msg: Omit<DbMessage, "id" | "created_at">,
): Promise<DbMessage | null> {
  const { data, error } = await supabase
    .from("messages")
    .insert(msg)
    .select()
    .single();
  if (error) {
    console.error("Supabase insertMessage:", error);
    return null;
  }
  return data;
}

export async function markMessageRead(
  msgId: string,
  role: string,
): Promise<void> {
  // Use Postgres array_append to atomically add the role
  const { error } = await supabase.rpc("mark_read", {
    msg_id: msgId,
    reader: role,
  });
  if (error) console.error("Supabase markRead:", error);
}

export async function deleteMessages(qNum: number): Promise<boolean> {
  const { error } = await supabase.from("messages").delete().eq("q_num", qNum);
  if (error) {
    console.error("Supabase deleteMessages:", error);
    return false;
  }
  return true;
}

// ── Realtime Subscription ──────────────────────────

let _channel: RealtimeChannel | null = null;
type MessageCallback = (msg: DbMessage) => void;

export function subscribeMessages(
  onInsert: MessageCallback,
  onUpdate?: MessageCallback,
): void {
  if (_channel) _channel.unsubscribe();

  _channel = supabase
    .channel("messages-realtime")
    .on(
      "postgres_changes",
      { event: "INSERT", schema: "public", table: "messages" },
      (payload) => onInsert(payload.new as DbMessage),
    )
    .on(
      "postgres_changes",
      { event: "UPDATE", schema: "public", table: "messages" },
      (payload) => {
        if (onUpdate) onUpdate(payload.new as DbMessage);
      },
    )
    .subscribe();
}

export function unsubscribeMessages(): void {
  if (_channel) {
    _channel.unsubscribe();
    _channel = null;
  }
}

// ── Audit Trail Types ───────────────────────────
export interface DbAuditEntry {
  id?: string; // uuid, auto-generated by DB
  timestamp: string;
  user_role: string;
  action: string;
  target_id: string;
  field: string;
  old_value: string;
  new_value: string;
  detail: string;
}

// ── Audit Trail CRUD ────────────────────────────

export async function fetchAuditLog(limit = 200): Promise<DbAuditEntry[]> {
  const { data, error } = await supabase
    .from("audit_log")
    .select("*")
    .order("timestamp", { ascending: false })
    .limit(limit);
  if (error) {
    console.error("Supabase fetchAuditLog:", error);
    return [];
  }
  return data ?? [];
}

export async function insertAuditEntry(
  entry: Omit<DbAuditEntry, "id">,
): Promise<DbAuditEntry | null> {
  const { data, error } = await supabase
    .from("audit_log")
    .insert(entry)
    .select()
    .single();
  if (error) {
    console.error("Supabase insertAuditEntry:", error);
    return null;
  }
  return data;
}

export async function insertAuditBatch(
  entries: Omit<DbAuditEntry, "id">[],
): Promise<boolean> {
  if (entries.length === 0) return true;
  const { error } = await supabase.from("audit_log").insert(entries);
  if (error) {
    console.error("Supabase insertAuditBatch:", error);
    return false;
  }
  return true;
}

// ── Subscription / Tier ─────────────────────────

export interface DbSubscription {
  id: string;
  project_id: string;
  tier: string;
  max_seats: number;
  stripe_customer_id: string | null;
  created_at: string;
  updated_at: string;
}

export async function fetchProjectTier(
  projectId: string,
): Promise<{ tier: string; maxSeats: number } | null> {
  const { data, error } = await supabase
    .from("subscriptions")
    .select("tier, max_seats")
    .eq("project_id", projectId)
    .single();
  if (error) {
    // Table may not exist yet — fall back gracefully
    if (error.code !== "PGRST116") {
      console.warn("Supabase fetchProjectTier:", error.message);
    }
    return null;
  }
  return data ? { tier: data.tier, maxSeats: data.max_seats } : null;
}

/** Server-authoritative tab list — calls the get_allowed_tabs RPC.
 *  Cannot be spoofed client-side; the function reads from subscriptions. */
export async function fetchAllowedTabs(projectId: string): Promise<string[]> {
  const { data, error } = await supabase.rpc("get_allowed_tabs", {
    p_project_id: projectId,
  });
  if (error) {
    console.warn("fetchAllowedTabs:", error.message);
    return ["dual-track", "gates", "timeline", "budget", "predicate-finder"];
  }
  return (
    data ?? ["dual-track", "gates", "timeline", "budget", "predicate-finder"]
  );
}

// ── Document Control — DHF Upload ───────────────

export interface DbDhfDocument {
  id: string;
  project_id: string;
  dcn: string;
  category: string;
  title: string;
  version: string;
  status: string;
  owner: string;
  effective_date: string | null;
  next_review: string | null;
  revisions: unknown[];
  updated_at?: string;
}

export async function upsertDhfDocument(
  projectId: string,
  doc: Omit<DbDhfDocument, "updated_at">,
): Promise<boolean> {
  const { error } = await supabase
    .from("dhf_documents")
    .upsert({ ...doc, project_id: projectId }, { onConflict: "id" });
  if (error) {
    console.error("Supabase upsertDhfDocument:", error);
    return false;
  }
  return true;
}

export async function upsertDhfDocumentBatch(
  projectId: string,
  docs: Omit<DbDhfDocument, "updated_at">[],
): Promise<{ ok: number; failed: number }> {
  let ok = 0;
  let failed = 0;
  for (const doc of docs) {
    const success = await upsertDhfDocument(projectId, doc);
    if (success) ok++;
    else failed++;
  }
  return { ok, failed };
}
